### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-backend#1]

**Comment by pietervdvn** [comment]
I've added some very basic logging. Logfile is written to `./logs/`. We should check where they end up according to docker

**Comment by xivk** [comment]
The logs folder is mapped as a volume here:

https://github.com/anyways-open/cycling-backend/blob/master/scripts/run-docker.sh#L7

It should en up on the host machine.

**Comment by pietervdvn** [comment]
Basic logging lives at /var/app/logs.

Currently logged are:

- Requests
- Errors
- Maintenance such as reloading the routerDB
