### ISSUE TITLE
Routing bug - node network

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-backend#13]
![image](https://user-images.githubusercontent.com/1128068/54308022-01a56080-45c5-11e9-9c1d-e49b683a9765.png)

We need to:
- [ ] Verify that only the node networks are in fact used and not the other networks.
- [ ] Relax the prefer factor until these routes start making more sense.

**Comment by xivk** [comment]
These two narrow down the issue nicely:

![image](https://user-images.githubusercontent.com/1128068/54308232-74164080-45c5-11e9-8338-59cc3a804262.png)

7.21km

https://genk.anyways.eu/staging/?loc1=4.126588,51.189253&loc2=4.069880,51.211151&zoom=13.19&lat=51.207082&lng=4.125155&p=network&

This one:

![image](https://user-images.githubusercontent.com/1128068/54308264-927c3c00-45c5-11e9-8e75-0191e5d3b957.png)

5.38km

https://genk.anyways.eu/staging/?loc1=4.126251,51.190189&loc2=4.069880,51.211151&zoom=12.70&lat=51.198023&lng=4.118711&p=network&

Both seem to be taking the cycling network, one of them probably is on a different network or there is some unknown bug.

**Comment by he-ulg** [comment]
![Screenshot (67)](https://user-images.githubusercontent.com/8438349/54342780-a2376700-463d-11e9-9312-21c17873b4e6.png)

Upon reporting the above issue by Wim (going through Antwerp), I changed the origin to BXL and tested every 3 existing route planning modes. For 2 of them, I noticed a persistence for routing alongside the border with France:

![Screenshot (69)](https://user-images.githubusercontent.com/8438349/54343693-aa90a180-463f-11e9-89e3-50f1e8b0945b.png)
![Screenshot (70)](https://user-images.githubusercontent.com/8438349/54343705-afedec00-463f-11e9-987c-76c2963ef255.png)

Though I got the most strange routing result when I selected the fastest route mode as you can see below :

![Screenshot (71)](https://user-images.githubusercontent.com/8438349/54343771-d2800500-463f-11e9-84f7-7c8444fec05a.png)
