### ISSUE TITLE
Convert routes into one feature.

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-backend#5]
Convert routes into one feature to make them look better on the map, now the overlaps of the different line segments give an *ugly* line:

![image](https://user-images.githubusercontent.com/1128068/45754192-3c809a00-bc1b-11e8-9d88-bb06ac4d166b.png)

We want to get rid of the dots and have a nice continuous opacity...

**Comment by pietervdvn** [comment]
I've very pragmatically removed all but the last shapemetas. This might mean that coloring is broken.

**Comment by xivk** [comment]
Yes, we should rebuild the shapemetas per color or alternatively adjust the geojson serialization to fix this permanently.

**Comment by pietervdvn** [comment]
I've added a small extension method that filters the shapemeta based on colour.
