### ISSUE TITLE
Troubleshoot strange routing

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-backend#6]
Troubleshoot strange routing:

https://genk.anyways.eu/?loc1=5.506431215241548,50.966453123024706&loc2=5.51817538791849,50.96871959978702&

**Comment by xivk** [comment]
I cannot reproduce this issue. I created a test project to start unittesting the profiles from now on here:

https://github.com/anyways-open/routing-profiles/tree/master/testbench

@pietervdvn Can you verify this is the actual profile being used in the current deployment and if not update the routerdb?

**Comment by pietervdvn** [comment]
[This script](https://github.com/anyways-open/cycling-backend/blob/master/update-map.sh) runs daily. 

I've diffed them, and apart from whitespace, there are only minor differences. The most prominent difference is

    bicycle_balanced_factors_cycleway = {                           bicycle_balanced_factors_cycleway = {
    ["lane"] = prefer_factor,                                                |         ["lane"] = avoid_factor,

This is one of my own changes in an (unsuccessful) attempt to fix the weird routing.

Is the idea that all profiles will be centralized in the other repo? Then I'll remove the profile here and update the update script.

**Comment by xivk** [comment]
Yes, that's the idea, that the profiles are centralized there. We can unittest them, refine them, and safely use them anywhere. They are very easy to break.

Are you sure the data is reloaded in the API? Because the routing is different.

**Comment by pietervdvn** [comment]
The map update is now running, with the central profile. ~~Should be done in 15minutes.~~ Done

Does the backend automatically pick up the new routerdb? I thought it did, but is there a way to confirm this?

**Comment by xivk** [comment]
There is another profile here:

https://github.com/anyways-open/cycling-backend/blob/master/src/profiles/bicycle.lua

And I'm not sure, perhaps it does, you can check the code where it loads the routerdb.

**Comment by pietervdvn** [comment]
The last profile you linked is identical to the earlier removed profile. I've deleted it as well.

**Comment by pietervdvn** [comment]
I've manually restarted the docker container. The [strange route](https://genk.anyways.eu/?loc1=5.506431215241548,50.966453123024706&loc2=5.51817538791849,50.96871959978702&) is gone.
