### ISSUE TITLE
Setup automatic build & deployment

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-backend#7]
Setup automatic build on the build server & automatically deploy whatever is in master.

**Comment by pietervdvn** [comment]
*/1 *  *   *   *     cd /var/www/cycling-frontend && git pull

Cron pulls the git repo every minute, deployment is pretty automatic.

**Comment by xivk** [comment]
With this I also mean the backend. Not sure that's already done yet?

**Comment by pietervdvn** [comment]
No, backend hasn't been done yet.

Your earlier comments which were accidentally placed in #7:

> How to do this:
> 
>     Add a build to https://build.anyways.eu/
>     Push the docker image to docker hub (we have an account).
>     Update the docker image when there is a newer latest available.

> This one is an example where a docker container is built and pushed:
> 
> https://build.anyways.eu/viewType.html?buildTypeId=anyways_ViaOsmService_ViaOsmService
>

**Comment by xivk** [comment]
Ah yes, sorry ;-)

**Comment by pietervdvn** [comment]
I've done some attempt to set up automatic building and testing on the [build server.](https://build.anyways.eu/project.html?projectId=CyclingBackend)

Could you check everything? I just pressed the buttons that seemed right to me. I guess that the project should be listed under 'anyways' too? I have no idea on how to move it.

**Comment by xivk** [comment]
This is now pushed here: 

https://hub.docker.com/r/anywaysopen/cycling-backend/

**Comment by xivk** [comment]
The build is also moved to the anyways project.

**Comment by xivk** [comment]
Build information will also get pushed to github now, see here:

https://github.com/anyways-open/cycling-backend/commits/master

**Comment by xivk** [comment]
We should still:
- [x] Auto update the routerdb every night and reload the data.

**Comment by pietervdvn** [comment]
Automatically updating the routerdb daily is already installed for months.
I've had a look at autorenewing the SSL-certificate as well. I've installed a crontab to run `certbot renew` monthly. The certificate (expiring mid february) was not renewed automatically as being 'not due for renewal'. I hope to mitigate this this way.
