### ISSUE TITLE
Add the cycling networks to OSM

### ISSUE THREAD

**Issue by pietervdvn** [anyways-open/cycling-backend#9]
This issue tracks the progress of adding the proposed cycle routes of Genk into OSM.

# Tagging scheme

- `type=route`
-  `route=bicycle`
- `ref`=[1A|1B|...]
- `operator=Stad Genk`
- `state=proposed` (until the road markings are placed)
- `colour=<hex value>`
- `roundtrip=no`

# Routes to map

- [x] 1
  - [x] [Common Part](https://www.openstreetmap.org/relation/9055798)
  - [x] [1A](https://www.openstreetmap.org/relation/9052448)
  - [x]  [1B](https://www.openstreetmap.org/relation/9052728)
- [x] [2 link to osm](https://www.openstreetmap.org/relation/9061851)
  - [x] Clarification needed: [here](https://www.openstreetmap.org/#map=17/50.98035/5.49897) makes the 'official' map a weird tour over forests. 
  - [x] Same [here](https://www.openstreetmap.org/#map=17/50.99454/5.52855); Voorstel: Hermesdijkstraat
- [x] [3, Link to OSM](https://www.openstreetmap.org/relation/9073325)
- [x] [4 Link to OSM](https://www.openstreetmap.org/relation/9078056)
- [x] [5 Link to Osm](https://www.openstreetmap.org/relation/9081527)
- [x] [6 Link to OSM](https://www.openstreetmap.org/relation/9075163)

Overpass query with currently mapped data: https://overpass-turbo.eu/s/EjV

WMS: layer: http://files.itinero.tech/anyways/genk/fietsnet-tiles/{zoom}/{x}/{-y}.png

**Comment by xivk** [comment]
We use type=route then instead of planned_route? Good call on the other tags! :+1:

**Comment by pietervdvn** [comment]
Yes.

And I just followed [the wiki](https://wiki.openstreetmap.org/wiki/Relation:route)

**Comment by pietervdvn** [comment]
I've added the missing links in Genk2 in a way that looked logical to me, if wrong, I'm sure they'll point that out to us.
